/*
 * generated by Xtext
 */
package com.github.marook;

/**
 * Use this class to register components to be used within the IDE.
 */
public class RoxAppletBuilderDslUiModule extends com.github.marook.AbstractRoxAppletBuilderDslUiModule {

}
