/*
* generated by Xtext
*/
package com.github.marook.contentassist;

import com.github.marook.contentassist.AbstractRoxAppletBuilderDslProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class RoxAppletBuilderDslProposalProvider extends AbstractRoxAppletBuilderDslProposalProvider {

}
