/*
* generated by Xtext
*/
package com.github.marook.outline;

import org.eclipse.xtext.ui.common.editor.outline.transformer.AbstractDeclarativeSemanticModelTransformer;

/**
 * customization of the default outline structure
 * 
 */
public class RoxAppletBuilderDslTransformer extends AbstractDeclarativeSemanticModelTransformer {
	
}
